customhost = "addemployee.cujavq47oj5k.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "addemployee"
custombucket = "employee1311"
customregion = "us-west-2"
