customhost = "employee.c0keurpd5p2v.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployee07"
customregion = "us-east-2"
