customhost = "employee1311.c0keurpd5p2v.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee1311"
custombucket = "employee13"
customregion = "us-east-1"
